import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/services/AuthProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    default: "Next hero",
    template: "%s | Next Hero",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
        <AuthProvider>
      <body>
          <Navbar />
          <div className="md:w-10/12 mx-auto">{children}</div>
          <Footer />
      </body>
        </AuthProvider>
    </html>
  );
}
